easy_admin:
    site_name: 'Dorcas Entreprise'
    #site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />' Logo
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd / M / Y H:i:s'

    entities:
        # List the entity class name you want to manage
        #- App\Entity\Product
        #- App\Entity\User

        User:
            class: App\Entity\User
            list:
                fields: ['id',{ property: 'imageName', label:'Image pièce',type: 'image', base_path: '/images/pieces/' }, { property: 'username', label: 'Nom Utilisateur' }, 'email',{ property: 'enabled', label: 'Activé' },{ property: 'lastLogin', label: 'Connecté le' },'roles']
            
            show:
                fields:
                    - id
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - roles
                    - { property: 'imageName',label:'Image pièce', type: 'image', base_path: '/images/pieces/' } 
            
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Informations personnelles',icon: 'id-card-o' }
                    - civilite
                    - nom
                    - prenom
                    - telephone
                    - { property: 'username', label:'Nom Utilisateur'}
                    - email
                    - { property: 'datenaisssance', label:'Date naisssance'}
                    - { property: 'plainPassword',label:'Mot de passe' ,type: 'text', type_options: { required: false } }
                    - { property: 'imageFile',label:'Image pièce', type: 'file', base_path: base_path: '/images/pieces/' }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Adresse de facturation' }
                    - { property: 'nomtierce', label:'Nom'}
                    - { property: 'prenomtierce', label:'Prénom'}
                    - { property: 'societetierce', label:'Société'}
                    - { property: 'adressetierce', label:'Addresse'}
                    - { property: 'codepostaltierce', label:'Code Postal'}
                    - { property: 'villetierce', label:'Ville'}
                    - { property: 'paystierce', label:'Pays'}
                    - { property: 'phonetierce', label:'Téléphone'}

                    - { type: 'group', css_class: 'col-sm-6', label: 'Role et Activation compte' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - { property: 'enabled', label:'Activer'}

    design:
        menu:
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }
        assets:
            favicon: '/assets/backend/zebitcoin.png'

    list:
        max_results: 10
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
