easy_admin:
    site_name: 'Dorcas Entreprise'
    #site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />' Logo
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd / M / Y H:i:s'

    entities:
        # List the entity class name you want to manage
        #- App\Entity\Product
        #- App\Entity\User

        User:
            class: App\Entity\User
            list:
                fields: ['id', { property: 'username', label: 'Nom Utilisateur' }, 'email',{ property: 'enabled', label: 'Activé' },{ property: 'lastLogin', label: 'Connecté le' },'roles']
            
            show:
                fields:
                    - id
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - roles
                   # - { property: 'image', type: 'image', base_path: '/uploads/images/pieces/' }  ,'image', type: 'image', base_path: '/uploads/images/pieces'
            
            form:
                fields:
                    - username
                    - email
                    - enabled
                    #- { property: 'imageFile', type: 'file', base_path: base_path: '/uploads/images/pieces/' }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

    design:
        menu:
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }
        assets:
            favicon: '/assets/backend/zebitcoin.png'

    list:
        max_results: 10
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
