vich_uploader:
    db_driver: orm

    mappings:
        piece_image:
            uri_prefix: /image/upload
            upload_destination: '%kernel.project_dir%/https://res.cloudinary.com/hfajnfk3v/image/upload'
