<?php

namespace App\Repository;

/**
 * BitcoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitcoinRepository extends \Doctrine\ORM\EntityRepository
{


}
