<?php

namespace App\Repository;

/**
 * ModePayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePayementRepository extends \Doctrine\ORM\EntityRepository
{


}
